"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _DriveMode:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _DriveModeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DriveMode.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    INVALID: _DriveMode.ValueType  # 0
    USER: _DriveMode.ValueType  # 1
    PILOT: _DriveMode.ValueType  # 2

class DriveMode(_DriveMode, metaclass=_DriveModeEnumTypeWrapper): ...

INVALID: DriveMode.ValueType  # 0
USER: DriveMode.ValueType  # 1
PILOT: DriveMode.ValueType  # 2
global___DriveMode = DriveMode

class _TypeObject:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _TypeObjectEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TypeObject.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ANY: _TypeObject.ValueType  # 0
    CAR: _TypeObject.ValueType  # 1
    BUMP: _TypeObject.ValueType  # 2
    PLOT: _TypeObject.ValueType  # 3

class TypeObject(_TypeObject, metaclass=_TypeObjectEnumTypeWrapper): ...

ANY: TypeObject.ValueType  # 0
CAR: TypeObject.ValueType  # 1
BUMP: TypeObject.ValueType  # 2
PLOT: TypeObject.ValueType  # 3
global___TypeObject = TypeObject

@typing_extensions.final
class FrameRef(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    name: builtins.str
    id: builtins.str
    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        id: builtins.str = ...,
        created_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["created_at", b"created_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["created_at", b"created_at", "id", b"id", "name", b"name"]) -> None: ...

global___FrameRef = FrameRef

@typing_extensions.final
class FrameMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    FRAME_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> global___FrameRef: ...
    frame: builtins.bytes
    def __init__(
        self,
        *,
        id: global___FrameRef | None = ...,
        frame: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id", b"id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["frame", b"frame", "id", b"id"]) -> None: ...

global___FrameMessage = FrameMessage

@typing_extensions.final
class SteeringMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STEERING_FIELD_NUMBER: builtins.int
    CONFIDENCE_FIELD_NUMBER: builtins.int
    FRAME_REF_FIELD_NUMBER: builtins.int
    steering: builtins.float
    confidence: builtins.float
    @property
    def frame_ref(self) -> global___FrameRef: ...
    def __init__(
        self,
        *,
        steering: builtins.float = ...,
        confidence: builtins.float = ...,
        frame_ref: global___FrameRef | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["frame_ref", b"frame_ref"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["confidence", b"confidence", "frame_ref", b"frame_ref", "steering", b"steering"]) -> None: ...

global___SteeringMessage = SteeringMessage

@typing_extensions.final
class ThrottleMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    THROTTLE_FIELD_NUMBER: builtins.int
    CONFIDENCE_FIELD_NUMBER: builtins.int
    FRAME_REF_FIELD_NUMBER: builtins.int
    throttle: builtins.float
    confidence: builtins.float
    @property
    def frame_ref(self) -> global___FrameRef: ...
    def __init__(
        self,
        *,
        throttle: builtins.float = ...,
        confidence: builtins.float = ...,
        frame_ref: global___FrameRef | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["frame_ref", b"frame_ref"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["confidence", b"confidence", "frame_ref", b"frame_ref", "throttle", b"throttle"]) -> None: ...

global___ThrottleMessage = ThrottleMessage

@typing_extensions.final
class DriveModeMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DRIVE_MODE_FIELD_NUMBER: builtins.int
    drive_mode: global___DriveMode.ValueType
    def __init__(
        self,
        *,
        drive_mode: global___DriveMode.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["drive_mode", b"drive_mode"]) -> None: ...

global___DriveModeMessage = DriveModeMessage

@typing_extensions.final
class ObjectsMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OBJECTS_FIELD_NUMBER: builtins.int
    FRAME_REF_FIELD_NUMBER: builtins.int
    @property
    def objects(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Object]: ...
    @property
    def frame_ref(self) -> global___FrameRef: ...
    def __init__(
        self,
        *,
        objects: collections.abc.Iterable[global___Object] | None = ...,
        frame_ref: global___FrameRef | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["frame_ref", b"frame_ref"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["frame_ref", b"frame_ref", "objects", b"objects"]) -> None: ...

global___ObjectsMessage = ObjectsMessage

@typing_extensions.final
class Object(google.protobuf.message.Message):
    """BoundingBox that contains an object, coordinates as percent"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    LEFT_FIELD_NUMBER: builtins.int
    TOP_FIELD_NUMBER: builtins.int
    RIGHT_FIELD_NUMBER: builtins.int
    BOTTOM_FIELD_NUMBER: builtins.int
    CONFIDENCE_FIELD_NUMBER: builtins.int
    type: global___TypeObject.ValueType
    left: builtins.float
    top: builtins.float
    right: builtins.float
    bottom: builtins.float
    confidence: builtins.float
    def __init__(
        self,
        *,
        type: global___TypeObject.ValueType = ...,
        left: builtins.float = ...,
        top: builtins.float = ...,
        right: builtins.float = ...,
        bottom: builtins.float = ...,
        confidence: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["bottom", b"bottom", "confidence", b"confidence", "left", b"left", "right", b"right", "top", b"top", "type", b"type"]) -> None: ...

global___Object = Object

@typing_extensions.final
class SwitchRecordMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENABLED_FIELD_NUMBER: builtins.int
    enabled: builtins.bool
    def __init__(
        self,
        *,
        enabled: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["enabled", b"enabled"]) -> None: ...

global___SwitchRecordMessage = SwitchRecordMessage

@typing_extensions.final
class RoadMessage(google.protobuf.message.Message):
    """Road description"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTOUR_FIELD_NUMBER: builtins.int
    ELLIPSE_FIELD_NUMBER: builtins.int
    FRAME_REF_FIELD_NUMBER: builtins.int
    @property
    def contour(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Point]:
        """list of points that describes road contour"""
    @property
    def ellipse(self) -> global___Ellipse:
        """rotated ellipse that fit road contour"""
    @property
    def frame_ref(self) -> global___FrameRef:
        """Reference to the frame used for compute"""
    def __init__(
        self,
        *,
        contour: collections.abc.Iterable[global___Point] | None = ...,
        ellipse: global___Ellipse | None = ...,
        frame_ref: global___FrameRef | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["ellipse", b"ellipse", "frame_ref", b"frame_ref"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["contour", b"contour", "ellipse", b"ellipse", "frame_ref", b"frame_ref"]) -> None: ...

global___RoadMessage = RoadMessage

@typing_extensions.final
class Point(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    x: builtins.int
    y: builtins.int
    def __init__(
        self,
        *,
        x: builtins.int = ...,
        y: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["x", b"x", "y", b"y"]) -> None: ...

global___Point = Point

@typing_extensions.final
class Ellipse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CENTER_FIELD_NUMBER: builtins.int
    WIDTH_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    ANGLE_FIELD_NUMBER: builtins.int
    CONFIDENCE_FIELD_NUMBER: builtins.int
    @property
    def center(self) -> global___Point: ...
    width: builtins.int
    height: builtins.int
    angle: builtins.float
    confidence: builtins.float
    def __init__(
        self,
        *,
        center: global___Point | None = ...,
        width: builtins.int = ...,
        height: builtins.int = ...,
        angle: builtins.float = ...,
        confidence: builtins.float = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["center", b"center"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["angle", b"angle", "center", b"center", "confidence", b"confidence", "height", b"height", "width", b"width"]) -> None: ...

global___Ellipse = Ellipse

@typing_extensions.final
class RecordMessage(google.protobuf.message.Message):
    """Record message used to tensorflow learning"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FRAME_FIELD_NUMBER: builtins.int
    STEERING_FIELD_NUMBER: builtins.int
    AUTOPILOT_STEERING_FIELD_NUMBER: builtins.int
    DRIVE_MODE_FIELD_NUMBER: builtins.int
    RECORDSET_FIELD_NUMBER: builtins.int
    @property
    def frame(self) -> global___FrameMessage: ...
    @property
    def steering(self) -> global___SteeringMessage: ...
    @property
    def autopilot_steering(self) -> global___SteeringMessage: ...
    @property
    def drive_mode(self) -> global___DriveModeMessage: ...
    recordSet: builtins.str
    """Record set name"""
    def __init__(
        self,
        *,
        frame: global___FrameMessage | None = ...,
        steering: global___SteeringMessage | None = ...,
        autopilot_steering: global___SteeringMessage | None = ...,
        drive_mode: global___DriveModeMessage | None = ...,
        recordSet: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["autopilot_steering", b"autopilot_steering", "drive_mode", b"drive_mode", "frame", b"frame", "steering", b"steering"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["autopilot_steering", b"autopilot_steering", "drive_mode", b"drive_mode", "frame", b"frame", "recordSet", b"recordSet", "steering", b"steering"]) -> None: ...

global___RecordMessage = RecordMessage
